#pragma once

#define LFI_CONTEXT_OFFSET_HOST_SP 0x0

#ifdef __cplusplus
#include "lfi.h"

#define CHECK_FIELD_OFFSET(offset_val, field)                                  \
  static_assert(offset_val == __builtin_offsetof(LFIContext, field));

CHECK_FIELD_OFFSET(LFI_CONTEXT_OFFSET_HOST_SP, kstackp);
#endif

#if defined(_M_X64) || defined(__x86_64__)

#define LFI_CONTEXT_OFFSET_RSP      0x10
#define LFI_CONTEXT_OFFSET_RAX      0x18
#define LFI_CONTEXT_OFFSET_RCX      0x20
#define LFI_CONTEXT_OFFSET_RDX      0x28
#define LFI_CONTEXT_OFFSET_RBX      0x30
#define LFI_CONTEXT_OFFSET_RBP      0x38
#define LFI_CONTEXT_OFFSET_RSI      0x40
#define LFI_CONTEXT_OFFSET_RDI      0x48
#define LFI_CONTEXT_OFFSET_R8       0x50
#define LFI_CONTEXT_OFFSET_R9       0x58
#define LFI_CONTEXT_OFFSET_R10      0x60
#define LFI_CONTEXT_OFFSET_R11      0x68
#define LFI_CONTEXT_OFFSET_R12      0x70
#define LFI_CONTEXT_OFFSET_R13      0x78
#define LFI_CONTEXT_OFFSET_R14      0x80
#define LFI_CONTEXT_OFFSET_R15      0x88
#define LFI_CONTEXT_OFFSET_FS       0x90
#define LFI_CONTEXT_OFFSET_GS       0x98
#define LFI_CONTEXT_OFFSET_XMM0     0xa0
#define LFI_CONTEXT_OFFSET_XMM1     0xa8
#define LFI_CONTEXT_OFFSET_XMM2     0xb0
#define LFI_CONTEXT_OFFSET_XMM3     0xb8
#define LFI_CONTEXT_OFFSET_XMM4     0xc0
#define LFI_CONTEXT_OFFSET_XMM5     0xc8
#define LFI_CONTEXT_OFFSET_XMM6     0xd0
#define LFI_CONTEXT_OFFSET_XMM7     0xd8
#define LFI_CONTEXT_OFFSET_XMM8     0xe0
#define LFI_CONTEXT_OFFSET_XMM9     0xe8
#define LFI_CONTEXT_OFFSET_XMM10    0xf0
#define LFI_CONTEXT_OFFSET_XMM11    0xf8
#define LFI_CONTEXT_OFFSET_XMM12    0x100
#define LFI_CONTEXT_OFFSET_XMM13    0x108
#define LFI_CONTEXT_OFFSET_XMM14    0x110
#define LFI_CONTEXT_OFFSET_XMM15    0x118

#ifdef __cplusplus
CHECK_FIELD_OFFSET(LFI_CONTEXT_OFFSET_RSP,   regs.rsp);
CHECK_FIELD_OFFSET(LFI_CONTEXT_OFFSET_RAX,   regs.rax);
CHECK_FIELD_OFFSET(LFI_CONTEXT_OFFSET_RCX,   regs.rcx);
CHECK_FIELD_OFFSET(LFI_CONTEXT_OFFSET_RDX,   regs.rdx);
CHECK_FIELD_OFFSET(LFI_CONTEXT_OFFSET_RBX,   regs.rbx);
CHECK_FIELD_OFFSET(LFI_CONTEXT_OFFSET_RBP,   regs.rbp);
CHECK_FIELD_OFFSET(LFI_CONTEXT_OFFSET_RSI,   regs.rsi);
CHECK_FIELD_OFFSET(LFI_CONTEXT_OFFSET_RDI,   regs.rdi);
CHECK_FIELD_OFFSET(LFI_CONTEXT_OFFSET_R8,    regs.r8);
CHECK_FIELD_OFFSET(LFI_CONTEXT_OFFSET_R9,    regs.r9);
CHECK_FIELD_OFFSET(LFI_CONTEXT_OFFSET_R10,   regs.r10);
CHECK_FIELD_OFFSET(LFI_CONTEXT_OFFSET_R11,   regs.r11);
CHECK_FIELD_OFFSET(LFI_CONTEXT_OFFSET_R12,   regs.r12);
CHECK_FIELD_OFFSET(LFI_CONTEXT_OFFSET_R13,   regs.r13);
CHECK_FIELD_OFFSET(LFI_CONTEXT_OFFSET_R14,   regs.r14);
CHECK_FIELD_OFFSET(LFI_CONTEXT_OFFSET_R15,   regs.r15);
CHECK_FIELD_OFFSET(LFI_CONTEXT_OFFSET_FS,    regs.fs);
CHECK_FIELD_OFFSET(LFI_CONTEXT_OFFSET_GS,    regs.gs);
CHECK_FIELD_OFFSET(LFI_CONTEXT_OFFSET_XMM0,  regs.xmm[0]);
CHECK_FIELD_OFFSET(LFI_CONTEXT_OFFSET_XMM1,  regs.xmm[1]);
CHECK_FIELD_OFFSET(LFI_CONTEXT_OFFSET_XMM2,  regs.xmm[2]);
CHECK_FIELD_OFFSET(LFI_CONTEXT_OFFSET_XMM3,  regs.xmm[3]);
CHECK_FIELD_OFFSET(LFI_CONTEXT_OFFSET_XMM4,  regs.xmm[4]);
CHECK_FIELD_OFFSET(LFI_CONTEXT_OFFSET_XMM5,  regs.xmm[5]);
CHECK_FIELD_OFFSET(LFI_CONTEXT_OFFSET_XMM6,  regs.xmm[6]);
CHECK_FIELD_OFFSET(LFI_CONTEXT_OFFSET_XMM7,  regs.xmm[7]);
CHECK_FIELD_OFFSET(LFI_CONTEXT_OFFSET_XMM8,  regs.xmm[8]);
CHECK_FIELD_OFFSET(LFI_CONTEXT_OFFSET_XMM9,  regs.xmm[9]);
CHECK_FIELD_OFFSET(LFI_CONTEXT_OFFSET_XMM10, regs.xmm[10]);
CHECK_FIELD_OFFSET(LFI_CONTEXT_OFFSET_XMM11, regs.xmm[11]);
CHECK_FIELD_OFFSET(LFI_CONTEXT_OFFSET_XMM12, regs.xmm[12]);
CHECK_FIELD_OFFSET(LFI_CONTEXT_OFFSET_XMM13, regs.xmm[13]);
CHECK_FIELD_OFFSET(LFI_CONTEXT_OFFSET_XMM14, regs.xmm[14]);
CHECK_FIELD_OFFSET(LFI_CONTEXT_OFFSET_XMM15, regs.xmm[15]);
#endif

#elif defined(__aarch64__) || defined(_M_ARM64)

#define LFI_CONTEXT_OFFSET_X0 0x10
#define LFI_CONTEXT_OFFSET_X1 0x18
#define LFI_CONTEXT_OFFSET_X2 0x20
#define LFI_CONTEXT_OFFSET_X3 0x28
#define LFI_CONTEXT_OFFSET_X4 0x30
#define LFI_CONTEXT_OFFSET_X5 0x38
#define LFI_CONTEXT_OFFSET_X6 0x40
#define LFI_CONTEXT_OFFSET_X7 0x48
#define LFI_CONTEXT_OFFSET_X8 0x50
#define LFI_CONTEXT_OFFSET_X9 0x58
#define LFI_CONTEXT_OFFSET_X10 0x60
#define LFI_CONTEXT_OFFSET_X11 0x68
#define LFI_CONTEXT_OFFSET_X12 0x70
#define LFI_CONTEXT_OFFSET_X13 0x78
#define LFI_CONTEXT_OFFSET_X14 0x80
#define LFI_CONTEXT_OFFSET_X15 0x88
#define LFI_CONTEXT_OFFSET_X16 0x90
#define LFI_CONTEXT_OFFSET_X17 0x98
#define LFI_CONTEXT_OFFSET_X18 0xa0
#define LFI_CONTEXT_OFFSET_X19 0xa8
#define LFI_CONTEXT_OFFSET_X20 0xb0
#define LFI_CONTEXT_OFFSET_X21 0xb8
#define LFI_CONTEXT_OFFSET_X22 0xc0
#define LFI_CONTEXT_OFFSET_X23 0xc8
#define LFI_CONTEXT_OFFSET_X24 0xd0
#define LFI_CONTEXT_OFFSET_X25 0xd8
#define LFI_CONTEXT_OFFSET_X26 0xe0
#define LFI_CONTEXT_OFFSET_X27 0xe8
#define LFI_CONTEXT_OFFSET_X28 0xf0
#define LFI_CONTEXT_OFFSET_X29 0xf8
#define LFI_CONTEXT_OFFSET_X30 0x100
#define LFI_CONTEXT_OFFSET_SP 0x108
#define LFI_CONTEXT_OFFSET_NZCV 0x110
#define LFI_CONTEXT_OFFSET_FPSR 0x118
#define LFI_CONTEXT_OFFSET_Q0 0x128
#define LFI_CONTEXT_OFFSET_Q1 0x138
#define LFI_CONTEXT_OFFSET_Q2 0x148
#define LFI_CONTEXT_OFFSET_Q3 0x158
#define LFI_CONTEXT_OFFSET_Q4 0x168
#define LFI_CONTEXT_OFFSET_Q5 0x178
#define LFI_CONTEXT_OFFSET_Q6 0x188
#define LFI_CONTEXT_OFFSET_Q7 0x198
#define LFI_CONTEXT_OFFSET_Q8 0x1a8
#define LFI_CONTEXT_OFFSET_Q9 0x1b8
#define LFI_CONTEXT_OFFSET_Q10 0x1c8
#define LFI_CONTEXT_OFFSET_Q11 0x1d8
#define LFI_CONTEXT_OFFSET_Q12 0x1e8
#define LFI_CONTEXT_OFFSET_Q13 0x1f8
#define LFI_CONTEXT_OFFSET_Q14 0x208
#define LFI_CONTEXT_OFFSET_Q15 0x218
#define LFI_CONTEXT_OFFSET_Q16 0x228
#define LFI_CONTEXT_OFFSET_Q17 0x238
#define LFI_CONTEXT_OFFSET_Q18 0x248
#define LFI_CONTEXT_OFFSET_Q19 0x258
#define LFI_CONTEXT_OFFSET_Q20 0x268
#define LFI_CONTEXT_OFFSET_Q21 0x278
#define LFI_CONTEXT_OFFSET_Q22 0x288
#define LFI_CONTEXT_OFFSET_Q23 0x298
#define LFI_CONTEXT_OFFSET_Q24 0x2a8
#define LFI_CONTEXT_OFFSET_Q25 0x2b8
#define LFI_CONTEXT_OFFSET_Q26 0x2c8
#define LFI_CONTEXT_OFFSET_Q27 0x2d8
#define LFI_CONTEXT_OFFSET_Q28 0x2e8
#define LFI_CONTEXT_OFFSET_Q29 0x2f8
#define LFI_CONTEXT_OFFSET_Q30 0x308
#define LFI_CONTEXT_OFFSET_Q31 0x318

#ifdef __cplusplus
CHECK_FIELD_OFFSET(LFI_CONTEXT_OFFSET_X0, regs.x0);
CHECK_FIELD_OFFSET(LFI_CONTEXT_OFFSET_X1, regs.x1);
CHECK_FIELD_OFFSET(LFI_CONTEXT_OFFSET_X2, regs.x2);
CHECK_FIELD_OFFSET(LFI_CONTEXT_OFFSET_X3, regs.x3);
CHECK_FIELD_OFFSET(LFI_CONTEXT_OFFSET_X4, regs.x4);
CHECK_FIELD_OFFSET(LFI_CONTEXT_OFFSET_X5, regs.x5);
CHECK_FIELD_OFFSET(LFI_CONTEXT_OFFSET_X6, regs.x6);
CHECK_FIELD_OFFSET(LFI_CONTEXT_OFFSET_X7, regs.x7);
CHECK_FIELD_OFFSET(LFI_CONTEXT_OFFSET_X8, regs.x8);
CHECK_FIELD_OFFSET(LFI_CONTEXT_OFFSET_X9, regs.x9);
CHECK_FIELD_OFFSET(LFI_CONTEXT_OFFSET_X10, regs.x10);
CHECK_FIELD_OFFSET(LFI_CONTEXT_OFFSET_X11, regs.x11);
CHECK_FIELD_OFFSET(LFI_CONTEXT_OFFSET_X12, regs.x12);
CHECK_FIELD_OFFSET(LFI_CONTEXT_OFFSET_X13, regs.x13);
CHECK_FIELD_OFFSET(LFI_CONTEXT_OFFSET_X14, regs.x14);
CHECK_FIELD_OFFSET(LFI_CONTEXT_OFFSET_X15, regs.x15);
CHECK_FIELD_OFFSET(LFI_CONTEXT_OFFSET_X16, regs.x16);
CHECK_FIELD_OFFSET(LFI_CONTEXT_OFFSET_X17, regs.x17);
CHECK_FIELD_OFFSET(LFI_CONTEXT_OFFSET_X18, regs.x18);
CHECK_FIELD_OFFSET(LFI_CONTEXT_OFFSET_X19, regs.x19);
CHECK_FIELD_OFFSET(LFI_CONTEXT_OFFSET_X20, regs.x20);
CHECK_FIELD_OFFSET(LFI_CONTEXT_OFFSET_X21, regs.x21);
CHECK_FIELD_OFFSET(LFI_CONTEXT_OFFSET_X22, regs.x22);
CHECK_FIELD_OFFSET(LFI_CONTEXT_OFFSET_X23, regs.x23);
CHECK_FIELD_OFFSET(LFI_CONTEXT_OFFSET_X24, regs.x24);
CHECK_FIELD_OFFSET(LFI_CONTEXT_OFFSET_X25, regs.x25);
CHECK_FIELD_OFFSET(LFI_CONTEXT_OFFSET_X26, regs.x26);
CHECK_FIELD_OFFSET(LFI_CONTEXT_OFFSET_X27, regs.x27);
CHECK_FIELD_OFFSET(LFI_CONTEXT_OFFSET_X28, regs.x28);
CHECK_FIELD_OFFSET(LFI_CONTEXT_OFFSET_X29, regs.x29);
CHECK_FIELD_OFFSET(LFI_CONTEXT_OFFSET_X30, regs.x30);
CHECK_FIELD_OFFSET(LFI_CONTEXT_OFFSET_SP, regs.sp);
CHECK_FIELD_OFFSET(LFI_CONTEXT_OFFSET_NZCV, regs.nzcv);
CHECK_FIELD_OFFSET(LFI_CONTEXT_OFFSET_FPSR, regs.fpsr);
CHECK_FIELD_OFFSET(LFI_CONTEXT_OFFSET_Q0, regs.vector[0]);
CHECK_FIELD_OFFSET(LFI_CONTEXT_OFFSET_Q1, regs.vector[2]);
CHECK_FIELD_OFFSET(LFI_CONTEXT_OFFSET_Q2, regs.vector[4]);
CHECK_FIELD_OFFSET(LFI_CONTEXT_OFFSET_Q3, regs.vector[6]);
CHECK_FIELD_OFFSET(LFI_CONTEXT_OFFSET_Q4, regs.vector[8]);
CHECK_FIELD_OFFSET(LFI_CONTEXT_OFFSET_Q5, regs.vector[10]);
CHECK_FIELD_OFFSET(LFI_CONTEXT_OFFSET_Q6, regs.vector[12]);
CHECK_FIELD_OFFSET(LFI_CONTEXT_OFFSET_Q7, regs.vector[14]);
CHECK_FIELD_OFFSET(LFI_CONTEXT_OFFSET_Q8, regs.vector[16]);
CHECK_FIELD_OFFSET(LFI_CONTEXT_OFFSET_Q9, regs.vector[18]);
CHECK_FIELD_OFFSET(LFI_CONTEXT_OFFSET_Q10, regs.vector[20]);
CHECK_FIELD_OFFSET(LFI_CONTEXT_OFFSET_Q11, regs.vector[22]);
CHECK_FIELD_OFFSET(LFI_CONTEXT_OFFSET_Q12, regs.vector[24]);
CHECK_FIELD_OFFSET(LFI_CONTEXT_OFFSET_Q13, regs.vector[26]);
CHECK_FIELD_OFFSET(LFI_CONTEXT_OFFSET_Q14, regs.vector[28]);
CHECK_FIELD_OFFSET(LFI_CONTEXT_OFFSET_Q15, regs.vector[30]);
CHECK_FIELD_OFFSET(LFI_CONTEXT_OFFSET_Q16, regs.vector[32]);
CHECK_FIELD_OFFSET(LFI_CONTEXT_OFFSET_Q17, regs.vector[34]);
CHECK_FIELD_OFFSET(LFI_CONTEXT_OFFSET_Q18, regs.vector[36]);
CHECK_FIELD_OFFSET(LFI_CONTEXT_OFFSET_Q19, regs.vector[38]);
CHECK_FIELD_OFFSET(LFI_CONTEXT_OFFSET_Q20, regs.vector[40]);
CHECK_FIELD_OFFSET(LFI_CONTEXT_OFFSET_Q21, regs.vector[42]);
CHECK_FIELD_OFFSET(LFI_CONTEXT_OFFSET_Q22, regs.vector[44]);
CHECK_FIELD_OFFSET(LFI_CONTEXT_OFFSET_Q23, regs.vector[46]);
CHECK_FIELD_OFFSET(LFI_CONTEXT_OFFSET_Q24, regs.vector[48]);
CHECK_FIELD_OFFSET(LFI_CONTEXT_OFFSET_Q25, regs.vector[50]);
CHECK_FIELD_OFFSET(LFI_CONTEXT_OFFSET_Q26, regs.vector[52]);
CHECK_FIELD_OFFSET(LFI_CONTEXT_OFFSET_Q27, regs.vector[54]);
CHECK_FIELD_OFFSET(LFI_CONTEXT_OFFSET_Q28, regs.vector[56]);
CHECK_FIELD_OFFSET(LFI_CONTEXT_OFFSET_Q29, regs.vector[58]);
CHECK_FIELD_OFFSET(LFI_CONTEXT_OFFSET_Q30, regs.vector[60]);
CHECK_FIELD_OFFSET(LFI_CONTEXT_OFFSET_Q31, regs.vector[62]);
#endif

#else
#error "Unknown architecture"
#endif

