#pragma once

#if defined(_M_X64) || defined(__x86_64__)

#define LFI_CONTEXT_OFFSET_HOST_RSP 0x0
#define LFI_CONTEXT_OFFSET_RSP      0x10
#define LFI_CONTEXT_OFFSET_RAX      0x18
#define LFI_CONTEXT_OFFSET_RCX      0x20
#define LFI_CONTEXT_OFFSET_RDX      0x28
#define LFI_CONTEXT_OFFSET_RBX      0x30
#define LFI_CONTEXT_OFFSET_RBP      0x38
#define LFI_CONTEXT_OFFSET_RSI      0x40
#define LFI_CONTEXT_OFFSET_RDI      0x48
#define LFI_CONTEXT_OFFSET_R8       0x50
#define LFI_CONTEXT_OFFSET_R9       0x58
#define LFI_CONTEXT_OFFSET_R10      0x60
#define LFI_CONTEXT_OFFSET_R11      0x68
#define LFI_CONTEXT_OFFSET_R12      0x70
#define LFI_CONTEXT_OFFSET_R13      0x78
#define LFI_CONTEXT_OFFSET_R14      0x80
#define LFI_CONTEXT_OFFSET_R15      0x88
#define LFI_CONTEXT_OFFSET_FS       0x90
#define LFI_CONTEXT_OFFSET_GS       0x98
#define LFI_CONTEXT_OFFSET_XMM0     0xa0
#define LFI_CONTEXT_OFFSET_XMM1     0xa8
#define LFI_CONTEXT_OFFSET_XMM2     0xb0
#define LFI_CONTEXT_OFFSET_XMM3     0xb8
#define LFI_CONTEXT_OFFSET_XMM4     0xc0
#define LFI_CONTEXT_OFFSET_XMM5     0xc8
#define LFI_CONTEXT_OFFSET_XMM6     0xd0
#define LFI_CONTEXT_OFFSET_XMM7     0xd8
#define LFI_CONTEXT_OFFSET_XMM8     0xe0
#define LFI_CONTEXT_OFFSET_XMM9     0xe8
#define LFI_CONTEXT_OFFSET_XMM10    0xf0
#define LFI_CONTEXT_OFFSET_XMM11    0xf8
#define LFI_CONTEXT_OFFSET_XMM12    0x100
#define LFI_CONTEXT_OFFSET_XMM13    0x108
#define LFI_CONTEXT_OFFSET_XMM14    0x110
#define LFI_CONTEXT_OFFSET_XMM15    0x118

#ifdef __cplusplus

#include "lfi.h"

#define CHECK_FIELD_OFFSET(offset_val, field)                                  \
  static_assert(offset_val == __builtin_offsetof(LFIContext, field));

CHECK_FIELD_OFFSET(LFI_CONTEXT_OFFSET_HOST_RSP, kstackp);

CHECK_FIELD_OFFSET(LFI_CONTEXT_OFFSET_RSP,   regs.rsp);
CHECK_FIELD_OFFSET(LFI_CONTEXT_OFFSET_RAX,   regs.rax);
CHECK_FIELD_OFFSET(LFI_CONTEXT_OFFSET_RCX,   regs.rcx);
CHECK_FIELD_OFFSET(LFI_CONTEXT_OFFSET_RDX,   regs.rdx);
CHECK_FIELD_OFFSET(LFI_CONTEXT_OFFSET_RBX,   regs.rbx);
CHECK_FIELD_OFFSET(LFI_CONTEXT_OFFSET_RBP,   regs.rbp);
CHECK_FIELD_OFFSET(LFI_CONTEXT_OFFSET_RSI,   regs.rsi);
CHECK_FIELD_OFFSET(LFI_CONTEXT_OFFSET_RDI,   regs.rdi);
CHECK_FIELD_OFFSET(LFI_CONTEXT_OFFSET_R8,    regs.r8);
CHECK_FIELD_OFFSET(LFI_CONTEXT_OFFSET_R9,    regs.r9);
CHECK_FIELD_OFFSET(LFI_CONTEXT_OFFSET_R10,   regs.r10);
CHECK_FIELD_OFFSET(LFI_CONTEXT_OFFSET_R11,   regs.r11);
CHECK_FIELD_OFFSET(LFI_CONTEXT_OFFSET_R12,   regs.r12);
CHECK_FIELD_OFFSET(LFI_CONTEXT_OFFSET_R13,   regs.r13);
CHECK_FIELD_OFFSET(LFI_CONTEXT_OFFSET_R14,   regs.r14);
CHECK_FIELD_OFFSET(LFI_CONTEXT_OFFSET_R15,   regs.r15);
CHECK_FIELD_OFFSET(LFI_CONTEXT_OFFSET_FS,    regs.fs);
CHECK_FIELD_OFFSET(LFI_CONTEXT_OFFSET_GS,    regs.gs);
CHECK_FIELD_OFFSET(LFI_CONTEXT_OFFSET_XMM0,  regs.xmm[0]);
CHECK_FIELD_OFFSET(LFI_CONTEXT_OFFSET_XMM1,  regs.xmm[1]);
CHECK_FIELD_OFFSET(LFI_CONTEXT_OFFSET_XMM2,  regs.xmm[2]);
CHECK_FIELD_OFFSET(LFI_CONTEXT_OFFSET_XMM3,  regs.xmm[3]);
CHECK_FIELD_OFFSET(LFI_CONTEXT_OFFSET_XMM4,  regs.xmm[4]);
CHECK_FIELD_OFFSET(LFI_CONTEXT_OFFSET_XMM5,  regs.xmm[5]);
CHECK_FIELD_OFFSET(LFI_CONTEXT_OFFSET_XMM6,  regs.xmm[6]);
CHECK_FIELD_OFFSET(LFI_CONTEXT_OFFSET_XMM7,  regs.xmm[7]);
CHECK_FIELD_OFFSET(LFI_CONTEXT_OFFSET_XMM8,  regs.xmm[8]);
CHECK_FIELD_OFFSET(LFI_CONTEXT_OFFSET_XMM9,  regs.xmm[9]);
CHECK_FIELD_OFFSET(LFI_CONTEXT_OFFSET_XMM10, regs.xmm[10]);
CHECK_FIELD_OFFSET(LFI_CONTEXT_OFFSET_XMM11, regs.xmm[11]);
CHECK_FIELD_OFFSET(LFI_CONTEXT_OFFSET_XMM12, regs.xmm[12]);
CHECK_FIELD_OFFSET(LFI_CONTEXT_OFFSET_XMM13, regs.xmm[13]);
CHECK_FIELD_OFFSET(LFI_CONTEXT_OFFSET_XMM14, regs.xmm[14]);
CHECK_FIELD_OFFSET(LFI_CONTEXT_OFFSET_XMM15, regs.xmm[15]);

#endif

#else
#error "Unknown architecture"
#endif

